browsers:
  - name: chrome
    version: latest
    platform: Windows 10
  - name: firefox
    version: latest
    platform: Windows 10
  - name: safari
    version: latest
    platform: Mac 10.13
  - name: microsoftedge
    version: latest
    platform: Windows 10
  - name: ie
    version: latest
    platform: Windows 10

# Force browserify to use latest buffer@5.
# Ideally we'd use latest browserify to achieve that,
# but airtap currently depends on browserify@13.
browserify:
  - require: "buffer/"
    expose: "buffer"
