providers:
  - airtap-sauce

browsers:
  - name: chrome
  - name: firefox
  - name: safari
  - name: edge
  - name: ie
  - name: iphone
  - name: chrome for android

presets:
  local:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
      - name: firefox
